# Environment-specific values: development
environment: development

replicaCount: 1

image:
  repository: ghcr.io/itsumohitoride/actividad-3-vf-1-microservice
  tag: 026817e
  pullPolicy: Always

service:
  type: NodePort

config:
  springProfilesActive: dev
