# Environment-specific values: development
global:
  environment: development

replicaCount: 1

image:
  repository: ghcr.io/itsumohitoride/actividad-3-vf-1-microservice
  tag: 07ab88c
  pullPolicy: Always

service:
  type: NodePort

ingress:
  enabled: false

config:
  springProfilesActive: dev
