# Environment-specific values: staging
environment: staging

replicaCount: 2

image:
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: staging.microservice.local

config:
  springProfilesActive: staging
