# Environment-specific values: production
environment: production

replicaCount: 3

image:
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: api.microservice.com

config:
  springProfilesActive: prod
