apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - install.yaml
  - project.yaml
  - application.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: microservice
    includeSelectors: true
